//! Generated gRPC code for proto/agent.proto (tonic + prost, zstd), plus the validating conversions.
//!
//! Owned by prompt 01. Read `AGENTS.md` and `prompts/01*.md` before changing this crate.
//! This crate is a contract path: changes go through the `lanekeeper-contract-change` process.
//!
//! - [`pb`]: the generated messages, clients and servers. Nothing outside this crate should build or read
//!   them directly; use [`convert`], which validates (S11) and returns the domain wire types.
//! - [`limits`]: the size limits that the hub, the agent and the sentinel share.
//! - [`grpc`]: zstd-enabled, size-limited constructors for the generated clients and servers.
#![forbid(unsafe_code)]
// The `Errors` section of every conversion would repeat `ConvertError`'s own docs.
#![allow(clippy::missing_errors_doc, clippy::must_use_candidate)]

pub mod convert;
pub mod grpc;
pub mod limits;

/// The code generated by `build.rs` from `proto/agent.proto`.
///
/// Generated code does not follow the workspace's pedantic style, so the lints are relaxed here and only here.
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    missing_docs,
    missing_debug_implementations,
    unreachable_pub,
    unused_qualifications
)]
pub mod pb {
    tonic::include_proto!("lanekeeper.agent.v1");
}

/// `Debug` for [`pb::JoinRequest`] is written by hand: the generated one would print the tokens (S7, S21).
impl std::fmt::Debug for pb::JoinRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let credential = match &self.credential {
            Some(pb::join_request::Credential::GoogleIdToken(_)) => "google_id_token: [redacted]",
            Some(pb::join_request::Credential::JoinToken(_)) => "join_token: [redacted]",
            None => "none",
        };
        f.debug_struct("JoinRequest")
            .field("swimlane_id", &self.swimlane_id)
            .field("csr_der_len", &self.csr_der.len())
            .field("credential", &format_args!("{credential}"))
            .field("kind", &self.kind)
            .finish()
    }
}
